version: "3.9"
services:
  db:
    image: mariadb:10.8.3-jammy
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: quizzako
      MARIADB_DATABASE: quizzako